language: python

python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- pypy
- pypy3
    
notifications:
  email:
    recipients:
      - rinat.sabitov@gmail.com
    on_success: change
    on_failure: change

install:
- pip install -r tests/requirements.txt
- pip install coveralls
- if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi

script:
- nosetests --with-coverage --cover-erase --cover-package=couchdblogger
after_success:
- coveralls
